name: Label Approved VEP PRs
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  contents: read
  issues: write

jobs:
  check-vep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run VEP check script
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python automation/label-approved-veps.py
